# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "👊 TinBòta"
email: tinbota@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Un luogo dove raccogliere tutte le informazioni sull'emergenza del nuovo Coronavirus COVID-19 a San Marino: notizie, dati, provvedimenti, informazioni, ma anche consigli su come affrontare le limitazioni.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tinbota.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  tinbota
footer_content: "<b>Disclaimer</b>: le informazioni contenute su questo sito vengono fornite senza alcuna garanzia in merito all'affidabilità e all'esattezza dei dati riportati. Dati, nomi e marchi vengono citati solo a scopo informativo, senza alcuna affiliazione ad aziende terze. Per segnalazioni, scrivere a <a href='mailto:tinbota@icloud.com'>tinbota@icloud.com</a>, oppure <a href='https://github.com/tinbota/tinbota.github.io/issues/new'>aprire una issue su GitHub</a>.<br/>"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
plugins:
  - jekyll-diagrams

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
